mkdir "Lesson 4B_ Content Providers"
copy ..\"Developing Android Apps Lession4B"\"4b_01_Why Content Providers Matter.srt"                         "Lesson 4B_ Content Providers"\"01 - Why Content Providers Matter.chs.srt"
copy ..\"Developing Android Apps Lession4B"\"4b_02_Create a Content Provider.srt"                            "Lesson 4B_ Content Providers"\"02 - Create a Content Provider.chs.srt"
copy ..\"Developing Android Apps Lession4B"\"4b_03_Explain our Changes to WeatherContract.srt"               "Lesson 4B_ Content Providers"\"03 - Explain our Changes to WeatherContract.chs.srt"
copy ..\"Developing Android Apps Lession4B"\"4b_04_Add a Weather w_Location UriBuilder Quiz.srt"             "Lesson 4B_ Content Providers"\"04 - Add a Weather wLocation UriBuilder Quiz.chs.srt"
copy ..\"Developing Android Apps Lession4B"\"4b_05_Weather w_Location UriBuilder Solution.srt"               "Lesson 4B_ Content Providers"\"05 - Weather wLocation UriBuilder Solution.chs.srt"
copy ..\"Developing Android Apps Lession4B"\"4b_06_Understand the UriMatcher.srt"                            "Lesson 4B_ Content Providers"\"06 - Understand the UriMatcher.chs.srt"
copy ..\"Developing Android Apps Lession4B"\"4b_07_Write the UriMatcher Quiz.srt"                            "Lesson 4B_ Content Providers"\"07 - Write the UriMatcher Quiz.chs.srt"
copy ..\"Developing Android Apps Lession4B"\"4b_08_Write the UriMatcher Solution.srt"                        "Lesson 4B_ Content Providers"\"08 - Write the UriMatcher Solution.chs.srt"
copy ..\"Developing Android Apps Lession4B"\"4b_09_Register the Content Provider Quiz.srt"                   "Lesson 4B_ Content Providers"\"09 - Register the Content Provider Quiz.chs.srt"
copy ..\"Developing Android Apps Lession4B"\"4b_10_Register the Content Provider Solution.srt"               "Lesson 4B_ Content Providers"\"10 - Register the Content Provider Solution.chs.srt"
copy ..\"Developing Android Apps Lession4B"\"4b_11_Code the ContentProvider onCreate.srt"                    "Lesson 4B_ Content Providers"\"11 - Code the ContentProvider onCreate.chs.srt"
copy ..\"Developing Android Apps Lession4B"\"4b_12_Code the ContentProvider getType Quiz.srt"                "Lesson 4B_ Content Providers"\"12 - Code the ContentProvider getType Quiz.chs.srt"
copy ..\"Developing Android Apps Lession4B"\"4b_13_ContentProvider getType Solution.srt"                     "Lesson 4B_ Content Providers"\"13 - ContentProvider getType Solution.chs.srt"
copy ..\"Developing Android Apps Lession4B"\"4b_14_Code the ContentProvider query().srt"                     "Lesson 4B_ Content Providers"\"14 - Code the ContentProvider query.chs.srt"
copy ..\"Developing Android Apps Lession4B"\"4b_15_Weather and Location queries Quiz.srt"                    "Lesson 4B_ Content Providers"\"15 - Weather and Location queries Quiz.chs.srt"
copy ..\"Developing Android Apps Lession4B"\"4b_16_Weather and Location queries Solution.srt"                "Lesson 4B_ Content Providers"\"16 - Weather and Location queries Solution.chs.srt"
copy ..\"Developing Android Apps Lession4B"\"4b_17_Talking about our JOIN.srt"                               "Lesson 4B_ Content Providers"\"17 - Talking about our JOIN.chs.srt"
copy ..\"Developing Android Apps Lession4B"\"4b_18_Code the ContentProvider Insert.srt"                      "Lesson 4B_ Content Providers"\"18 - Code the ContentProvider Insert.chs.srt"
copy ..\"Developing Android Apps Lession4B"\"4b_19_Finish Insert - Quiz.srt"                                 "Lesson 4B_ Content Providers"\"19 - Finish Insert - Quiz.chs.srt"
copy ..\"Developing Android Apps Lession4B"\"4b_20_Finish Insert - Solution.srt"                             "Lesson 4B_ Content Providers"\"20 - Finish Insert - Solution.chs.srt"
copy ..\"Developing Android Apps Lession4B"\"4b_21_Update and Delete - Quiz.srt"                             "Lesson 4B_ Content Providers"\"21 - Update and Delete - Quiz.chs.srt"
copy ..\"Developing Android Apps Lession4B"\"4b_22_Update and Delete - Solution.srt"                         "Lesson 4B_ Content Providers"\"22 - Update and Delete - Solution.chs.srt"
copy ..\"Developing Android Apps Lession4B"\"4b_23_Efficient Updates _ Inserts.srt"                          "Lesson 4B_ Content Providers"\"23 - Efficient Updates  Inserts.chs.srt"
copy ..\"Developing Android Apps Lession4B"\"4b_24_ContentProvider Redux.srt"                                "Lesson 4B_ Content Providers"\"24 - ContentProvider Redux.chs.srt"
copy ..\"Developing Android Apps Lession4B"\"4b_25_Create FetchWeather Task.srt"                             "Lesson 4B_ Content Providers"\"25 - Create FetchWeather Task.chs.srt"
copy ..\"Developing Android Apps Lession4B"\"4b_26_Inserts with ContentProvider - Quiz.srt"                  "Lesson 4B_ Content Providers"\"26 - Inserts with ContentProvider - Quiz.chs.srt"
copy ..\"Developing Android Apps Lession4B"\"4b_27_Inserts with ContentProvider - Solution.srt"              "Lesson 4B_ Content Providers"\"27 - Inserts with ContentProvider - Solution.chs.srt"
copy ..\"Developing Android Apps Lession4B"\"4b_28_BulkInserts with ContentProvider - Quiz.srt"              "Lesson 4B_ Content Providers"\"28 - BulkInserts with ContentProvider - Quiz.chs.srt"
copy ..\"Developing Android Apps Lession4B"\"4b_29_BulkInserts w_ContentProvider - Solution.srt"             "Lesson 4B_ Content Providers"\"29 - BulkInserts wContentProvider - Solution.chs.srt"
