mkdir "Lesson 1_ Create Project Sunshine"
copy ..\"Developing Android Apps Lession1"\"01_01_Welcome to Developing Android Apps.srt"   "Lesson 1_ Create Project Sunshine"\"01 - Welcome to Developing Android Apps.chs.srt"
copy ..\"Developing Android Apps Lession1"\"01_02_Introducing Your Instructors.srt"         "Lesson 1_ Create Project Sunshine"\"02 - Introducing Your Instructors.chs.srt"
copy ..\"Developing Android Apps Lession1"\"01_03_Are you ready for this course.srt"        "Lesson 1_ Create Project Sunshine"\"03 - Are you ready for this course.chs.srt"
copy ..\"Developing Android Apps Lession1"\"01_04_Introducing Project Sunshine.srt"         "Lesson 1_ Create Project Sunshine"\"04 - Introducing Project Sunshine.chs.srt"
copy ..\"Developing Android Apps Lession1"\"01_05_Course Goals and Prerequisites.srt"       "Lesson 1_ Create Project Sunshine"\"05 - Course Goals and Prerequisites.chs.srt"
copy ..\"Developing Android Apps Lession1"\"01_06_Introducing More Sunshine.srt"            "Lesson 1_ Create Project Sunshine"\"06 - Introducing More Sunshine.chs.srt"
copy ..\"Developing Android Apps Lession1"\"01_08_Create a New Android Studio Project.srt"  "Lesson 1_ Create Project Sunshine"\"07 - Create a New Android Studio Project.chs.srt" 
copy ..\"Developing Android Apps Lession1"\"01_09_Select a Minimum and Target SDK.srt"      "Lesson 1_ Create Project Sunshine"\"08 - Select a Minimum and Target SDK.chs.srt"
copy ..\"Developing Android Apps Lession1"\"01_10_Select a Target SDK.srt"                  "Lesson 1_ Create Project Sunshine"\"09 - Select a Target SDK.chs.srt"
copy ..\"Developing Android Apps Lession1"\"01_11_Select a Target SDK Solution.srt"         "Lesson 1_ Create Project Sunshine"\"10 - Select a Target SDK Solution.chs.srt"
copy ..\"Developing Android Apps Lession1"\"01_12_Finish Creating a New Project.srt"        "Lesson 1_ Create Project Sunshine"\"11 - Finish Creating a New Project.chs.srt"
copy ..\"Developing Android Apps Lession1"\"01_13_Launch Sunshine and Create an AVD.srt"    "Lesson 1_ Create Project Sunshine"\"14 - Launch Sunshine and Create an AVD.chs.srt"
copy ..\"Developing Android Apps Lession1"\"01_14_Android Software Stack and Gradle.srt"    "Lesson 1_ Create Project Sunshine"\"16 - Android Software Stack and Gradle.chs.srt"
copy ..\"Developing Android Apps Lession1"\"01_15_Debugging with a Physical Device.srt"     "Lesson 1_ Create Project Sunshine"\"17 - Debugging with a Physical Device.chs.srt"
copy ..\"Developing Android Apps Lession1"\"01_16_Launching on a Device.srt"                "Lesson 1_ Create Project Sunshine"\"18 - Launching on  a Device.chs.srt"
copy ..\"Developing Android Apps Lession1"\"01_17_Start to Build the App.srt"               "Lesson 1_ Create Project Sunshine"\"19 - Start to Build the App.chs.srt"
copy ..\"Developing Android Apps Lession1"\"01_18_Create a User Interface.srt"              "Lesson 1_ Create Project Sunshine"\"20 - Create a User Interface.chs.srt"
copy ..\"Developing Android Apps Lession1"\"01_19_UI Element Quiz.srt"                      "Lesson 1_ Create Project Sunshine"\"21 - UI Element Quiz.chs.srt"
copy ..\"Developing Android Apps Lession1"\"01_20_Add ListItem XML.srt"                     "Lesson 1_ Create Project Sunshine"\"22 - Add ListItem XML.chs.srt"
copy ..\"Developing Android Apps Lession1"\"01_21_Add ListItem XML.srt"                     "Lesson 1_ Create Project Sunshine"\"23 - Add ListItem XML.chs.srt"
copy ..\"Developing Android Apps Lession1"\"01_22_Introducing Responsive Design.srt"        "Lesson 1_ Create Project Sunshine"\"24 - Introducing Responsive Design.chs.srt"
copy ..\"Developing Android Apps Lession1"\"01_23_Why AbsoluteLayout Is Evil.srt"           "Lesson 1_ Create Project Sunshine"\"25 - Why AbsoluteLayout Is Evil.chs.srt"
copy ..\"Developing Android Apps Lession1"\"01_24_Responsive Design Thinking.srt"           "Lesson 1_ Create Project Sunshine"\"26 - Responsive Design Thinking.chs.srt"
copy ..\"Developing Android Apps Lession1"\"01_25_Layout Managers.srt"                      "Lesson 1_ Create Project Sunshine"\"27 - Layout Managers.chs.srt"
copy ..\"Developing Android Apps Lession1"\"01_26_ScrollViews vs ListViews.srt"             "Lesson 1_ Create Project Sunshine"\"28 - ScrollViews vs ListViews.chs.srt"
copy ..\"Developing Android Apps Lession1"\"01_27_Scroll Views vs ListViews.srt"            "Lesson 1_ Create Project Sunshine"\"29 - Scroll Views vs ListViews.chs.srt"
copy ..\"Developing Android Apps Lession1"\"01_28_ListView and Recycling.mp4.srt"           "Lesson 1_ Create Project Sunshine"\"30 - ListView and Recycling.chs.srt"
copy ..\"Developing Android Apps Lession1"\"01_29_Add ListView to layout.srt"               "Lesson 1_ Create Project Sunshine"\"31 - Add ListView to layout.chs.srt"
copy ..\"Developing Android Apps Lession1"\"01_30_Add ListView to layout.srt"               "Lesson 1_ Create Project Sunshine"\"32 - Add ListView to layout.chs.srt"
copy ..\"Developing Android Apps Lession1"\"01_31_Create Some Fake Data.srt"                "Lesson 1_ Create Project Sunshine"\"33 - Create Some Fake Data.chs.srt"
copy ..\"Developing Android Apps Lession1"\"01_32_Create Some Fake Data.srt"                "Lesson 1_ Create Project Sunshine"\"34 - Create Some Fake Data.chs.srt"
copy ..\"Developing Android Apps Lession1"\"01_33_Adapters.srt"                             "Lesson 1_ Create Project Sunshine"\"35 - Adapters.chs.srt"
copy ..\"Developing Android Apps Lession1"\"01_34_Initialize the Adapter.srt"               "Lesson 1_ Create Project Sunshine"\"36 - Initialize the Adapter.chs.srt"
copy ..\"Developing Android Apps Lession1"\"01_35_Initialize the Adapter Solution.srt"      "Lesson 1_ Create Project Sunshine"\"37 - Initialize the Adapter Solution.chs.srt"
copy ..\"Developing Android Apps Lession1"\"01_36_Finding Views findViewById().srt"         "Lesson 1_ Create Project Sunshine"\"38 - Finding Views findViewById.chs.srt"
copy ..\"Developing Android Apps Lession1"\"01_37_Finding Views findViewById().srt"         "Lesson 1_ Create Project Sunshine"\"39 - Finding Views findViewById.chs.srt"
copy ..\"Developing Android Apps Lession1"\"01_38_Great Work.srt"                           "Lesson 1_ Create Project Sunshine"\"40 - Great Work.chs.srt"
copy ..\"Developing Android Apps Lession1"\"01_39_Lesson One Recap.srt"                     "Lesson 1_ Create Project Sunshine"\"41 - Lesson One Recap.chs.srt"
copy ..\"Developing Android Apps Lession1"\"01_40_Storytime Android Platform.srt"           "Lesson 1_ Create Project Sunshine"\"42 - Storytime Android Platform.chs.srt"