mkdir "Lesson 2_ Connect Sunshine to the Cloud"
copy ..\"Developing Android Apps Lession2"\"02_01_Introduction.srt"                               "Lesson 2_ Connect Sunshine to the Cloud"\"01 - Introduction.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_02_Review Data Provided by Open Weather Map.srt"   "Lesson 2_ Connect Sunshine to the Cloud"\"02 - Review Data Provided by Open Weather Map.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_03_Try Out Web Queries.srt"                        "Lesson 2_ Connect Sunshine to the Cloud"\"03 - Try Out Web Queries.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_04_Find the Query We Want.srt"                     "Lesson 2_ Connect Sunshine to the Cloud"\"04 - Find the Query We Want.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_05_Find the Query We Want Solution.srt"            "Lesson 2_ Connect Sunshine to the Cloud"\"05 - Find the Query We Want Solution.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_06_HTTP Request for Weather Data.srt"              "Lesson 2_ Connect Sunshine to the Cloud"\"06 - HTTP Request for Weather Data.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_07_HTTP Requests.srt"                              "Lesson 2_ Connect Sunshine to the Cloud"\"07 - HTTP Requests.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_08_Logcat.srt"                                     "Lesson 2_ Connect Sunshine to the Cloud"\"08 - Logcat.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_09_Logging on Android.srt"                         "Lesson 2_ Connect Sunshine to the Cloud"\"09 - Logging on Android.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_10_Network Call.srt"                               "Lesson 2_ Connect Sunshine to the Cloud"\"10 - Network Call.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_11_What caused the crash Solution.srt"             "Lesson 2_ Connect Sunshine to the Cloud"\"11 - What caused the crash Solution.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_12_Main Thread vs Background Thread.srt"           "Lesson 2_ Connect Sunshine to the Cloud"\"12 - Main Thread vs Background Thread.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_13_Main Thread vs Background Thread Solution.srt"  "Lesson 2_ Connect Sunshine to the Cloud"\"13 - Main Thread vs Background Thread.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_14_Which Thread for AsyncTask.srt"                 "Lesson 2_ Connect Sunshine to the Cloud"\"14 - Which Thread for AsyncTask.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_15_Which Thread for AsyncTask Solution.srt"        "Lesson 2_ Connect Sunshine to the Cloud"\"15 - Which Thread for AsyncTask.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_16_Move to AsyncTask.srt"                          "Lesson 2_ Connect Sunshine to the Cloud"\"16 - Move to AsyncTask.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_17_Move to AsyncTask Solution.srt"                 "Lesson 2_ Connect Sunshine to the Cloud"\"17 - Move to AsyncTask.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_18_Add Refresh Button.srt"                         "Lesson 2_ Connect Sunshine to the Cloud"\"18 - Add Refresh Button.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_19_Why AsyncTask is Not Optimal.srt"               "Lesson 2_ Connect Sunshine to the Cloud"\"19 - Why AsyncTask is Not Optimal.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_20_Why AsyncTask is Not Optima Solution.srt"       "Lesson 2_ Connect Sunshine to the Cloud"\"20 - Why AsyncTask is Not Optimal.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_21_Better Ways to Sync.srt"                        "Lesson 2_ Connect Sunshine to the Cloud"\"21 - Better Ways to Sync.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_22_Menu Buttons.srt"                               "Lesson 2_ Connect Sunshine to the Cloud"\"22 - Menu Buttons.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_23_Refresh Button.srt"                             "Lesson 2_ Connect Sunshine to the Cloud"\"23 - Refresh Button.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_24_Refresh Button Solution.srt"                    "Lesson 2_ Connect Sunshine to the Cloud"\"24 - Refresh Button.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_25_Refresh Button Behavior.srt"                    "Lesson 2_ Connect Sunshine to the Cloud"\"25 - Refresh Button Behavior.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_26_Refresh Button Behavior Solution.srt"           "Lesson 2_ Connect Sunshine to the Cloud"\"26 - Refresh Button Behavior.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_27_Execute AsyncTask.srt"                          "Lesson 2_ Connect Sunshine to the Cloud"\"27 - Execute AsyncTask.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_28_Execute AsyncTask Solution.srt"                 "Lesson 2_ Connect Sunshine to the Cloud"\"28 - Execute AsyncTask.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_29_Permissions.srt"                                "Lesson 2_ Connect Sunshine to the Cloud"\"29 - Permissions.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_30_Permissions in the Manifest.srt"                "Lesson 2_ Connect Sunshine to the Cloud"\"30 - Permissions in the Manifest.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_31_Permissions in the Manifest Solution.srt"       "Lesson 2_ Connect Sunshine to the Cloud"\"31 - Permissions in the Manifest.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_32_Adding Internet Permission.srt"                 "Lesson 2_ Connect Sunshine to the Cloud"\"32 - Adding Internet Permission.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_33_Adding Internet Permission Solution.srt"        "Lesson 2_ Connect Sunshine to the Cloud"\"33 - Adding Internet Permission.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_34_Postal Code Param.srt"                          "Lesson 2_ Connect Sunshine to the Cloud"\"34 - Postal Code Param.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_35_Postal Code Param Solution.srt"                 "Lesson 2_ Connect Sunshine to the Cloud"\"35 - Postal Code Param.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_36_Identify Desired JSON Attributes.srt"           "Lesson 2_ Connect Sunshine to the Cloud"\"36 - Identify Desired JSON Attributes Quiz.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_37_Identify Desired JSON Attributes Solution.srt"  "Lesson 2_ Connect Sunshine to the Cloud"\"37 - Identify Desired JSON Attributes Sol.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_38_Parse Out the Max Temp.srt"                     "Lesson 2_ Connect Sunshine to the Cloud"\"40 - Parse Out the Max Temp.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_39_Parse Out the Max Temp Solution.srt"            "Lesson 2_ Connect Sunshine to the Cloud"\"41 - Parse Out the Max Temp.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_40_JSON Parsing.srt"                               "Lesson 2_ Connect Sunshine to the Cloud"\"42 - JSON Parsing.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_41_JSON Parsing Solution.srt"                      "Lesson 2_ Connect Sunshine to the Cloud"\"43 - JSON Parsing.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_42_Update the Adapter.srt"                         "Lesson 2_ Connect Sunshine to the Cloud"\"46 - Update the Adapter.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_43_Update the Adapter Solution.srt"                "Lesson 2_ Connect Sunshine to the Cloud"\"47 - Update the Adapter.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_44_Source Code for ArrayAdapter.srt"               "Lesson 2_ Connect Sunshine to the Cloud"\"48 - Source Code for ArrayAdapter.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_45_Take a Screenshot.srt"                          "Lesson 2_ Connect Sunshine to the Cloud"\"49 - Take a Screenshot.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_46_Done!.srt"                                      "Lesson 2_ Connect Sunshine to the Cloud"\"50 - Done.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_47_Lesson 2 Recap.srt"                             "Lesson 2_ Connect Sunshine to the Cloud"\"51 - Lesson 2 Recap.chs.srt"
copy ..\"Developing Android Apps Lession2"\"02_48_Storytime Android Consumer Platform.srt"        "Lesson 2_ Connect Sunshine to the Cloud"\"52 - Storytime Android Consumer Platform.chs.srt"
