mkdir "Lesson 6_ Services and Notifications"
copy ..\"Developing Android Apps Lession6"\"06_01_Intro to Lesson 6 - Developing Android Apps.srt"                      "Lesson 6_ Services and Notifications"\"01 - Intro to Lesson 6.chs.srt"
copy ..\"Developing Android Apps Lession6"\"06_02_Sunshine in the Background - Developing Android Apps.srt"             "Lesson 6_ Services and Notifications"\"02 - Sunshine in the Background.chs.srt"
copy ..\"Developing Android Apps Lession6"\"06_03_App Lifecycle and Services - Developing Android Apps.srt"             "Lesson 6_ Services and Notifications"\"03 - App Lifecycle and Services.chs.srt"
copy ..\"Developing Android Apps Lession6"\"06_04_Application Priority - Developing Android Apps.srt"                   "Lesson 6_ Services and Notifications"\"04 - Application Priority.chs.srt"
copy ..\"Developing Android Apps Lession6"\"06_05_Application Priority Solution.srt"                                    "Lesson 6_ Services and Notifications"\"05 - Application Priority.chs.srt"
copy ..\"Developing Android Apps Lession6"\"06_06_Using Services - Developing Android Apps.srt"                         "Lesson 6_ Services and Notifications"\"06 - Using Services.chs.srt"
copy ..\"Developing Android Apps Lession6"\"06_07_Using Services Solution.srt"                                          "Lesson 6_ Services and Notifications"\"07 - Using Services.chs.srt"
copy ..\"Developing Android Apps Lession6"\"06_08_Using Alarms - Developing Android Apps.srt"                           "Lesson 6_ Services and Notifications"\"08 - Using Alarms.chs.srt"
copy ..\"Developing Android Apps Lession6"\"06_09_Using Alarms Solution.srt"                                            "Lesson 6_ Services and Notifications"\"09 - Using Alarms.chs.srt"
copy ..\"Developing Android Apps Lession6"\"06_10_Transferring Data Efficiently - Developing Android Apps.srt"          "Lesson 6_ Services and Notifications"\"10 - Transferring Data Efficiently.chs.srt"
copy ..\"Developing Android Apps Lession6"\"06_11_Transferring Data Efficiently Solution.srt"                           "Lesson 6_ Services and Notifications"\"11 - Transferring Data Efficiently.chs.srt"
copy ..\"Developing Android Apps Lession6"\"06_12_The Cell Radio - Developing Android Apps.srt"                         "Lesson 6_ Services and Notifications"\"12 - The Cell Radio.chs.srt"
copy ..\"Developing Android Apps Lession6"\"06_13_The Cell Radio Solution.srt"                                          "Lesson 6_ Services and Notifications"\"13 - The Cell Radio.chs.srt"
copy ..\"Developing Android Apps Lession6"\"06_14_Big Cookie Model - Developing Android Apps.srt"                       "Lesson 6_ Services and Notifications"\"14 - Big Cookie Model.chs.srt"
copy ..\"Developing Android Apps Lession6"\"06_15_Data Transfer Best Practices - Developing Android Apps.srt"           "Lesson 6_ Services and Notifications"\"15 - Data Transfer Best Practices.chs.srt"
copy ..\"Developing Android Apps Lession6"\"06_16_Data Transfer Best Practices Solution.srt"                            "Lesson 6_ Services and Notifications"\"16 - Data Transfer Best Practices.chs.srt"
copy ..\"Developing Android Apps Lession6"\"06_17_Introducing SyncAdapters - Developing Android Apps.srt"               "Lesson 6_ Services and Notifications"\"17 - Introducing SyncAdapters.chs.srt"
copy ..\"Developing Android Apps Lession6"\"06_18_Introducing SyncAdapters Solution.srt"                                "Lesson 6_ Services and Notifications"\"18 - Introducing SyncAdapters.chs.srt"
copy ..\"Developing Android Apps Lession6"\"06_19_Finish the SyncAdapter - Developing Android Apps.srt"                 "Lesson 6_ Services and Notifications"\"20 - Finish the SyncAdapter.chs.srt"
copy ..\"Developing Android Apps Lession6"\"06_20_Finish the SyncAdapter Solution.srt"                                  "Lesson 6_ Services and Notifications"\"21 - Finish the SyncAdapter.chs.srt"
copy ..\"Developing Android Apps Lession6"\"06_21_Scheduled Synchronization Solution.srt"                               "Lesson 6_ Services and Notifications"\"25 - Scheduled Synchronization.chs.srt"
copy ..\"Developing Android Apps Lession6"\"06_22_Google cloud messaging - Developing Android Apps.srt"                 "Lesson 6_ Services and Notifications"\"27 - Google cloud messaging.chs.srt"
copy ..\"Developing Android Apps Lession6"\"06_23_Notifications Solution.srt"                                           "Lesson 6_ Services and Notifications"\"29 - Notifications.chs.srt"
copy ..\"Developing Android Apps Lession6"\"06_24_The Power of Notifications - Developing Android Apps.srt"             "Lesson 6_ Services and Notifications"\"31 - The Power of Notifications.chs.srt"
copy ..\"Developing Android Apps Lession6"\"06_25_Turning Weather Notifications On_Off - Developing Android Apps.srt"   "Lesson 6_ Services and Notifications"\"32 - Turning Weather Notifications OnOff.chs.srt"
copy ..\"Developing Android Apps Lession6"\"06_26_Turning Weather Notifications OnOff Solution.srt"                     "Lesson 6_ Services and Notifications"\"33 - Turning Weather Notifications OnOff.chs.srt"
copy ..\"Developing Android Apps Lession6"\"06_27_Delete Old Weather Data - Developing Android Apps.srt"                "Lesson 6_ Services and Notifications"\"34 - Delete Old Weather Data.chs.srt"
copy ..\"Developing Android Apps Lession6"\"06_28_Delete Old Weather Data - Solution.srt"                               "Lesson 6_ Services and Notifications"\"35 - Delete Old Weather Data - Solution.chs.srt"
copy ..\"Developing Android Apps Lession6"\"06_29_Update Map Intent - Developing Android Apps.srt"                      "Lesson 6_ Services and Notifications"\"36 - Update Map Intent.chs.srt"
copy ..\"Developing Android Apps Lession6"\"06_30_Update Map Intent - Solution.srt"                                     "Lesson 6_ Services and Notifications"\"37 - Update Map Intent - Solution.chs.srt"
copy ..\"Developing Android Apps Lession6"\"06_31_Lesson 6 Recap - Developing Android Apps.srt"                         "Lesson 6_ Services and Notifications"\"38 - Lesson 6 Recap.chs.srt"
copy ..\"Developing Android Apps Lession6"\"06_32_Storytime Future of Android - Developing Android Apps.srt"            "Lesson 6_ Services and Notifications"\"39 - Storytime Future of Android.chs.srt"
copy ..\"Developing Android Apps Lession6"\"06_33_Congratulations! Android Party! - Developing Android Apps.srt"        "Lesson 6_ Services and Notifications"\"40 - Congratulations Android Party.chs.srt"
