mkdir "Lesson 4C_ Hooking it Up with Loaders"
copy ..\"Developing Android Apps Lession4C"\"4c_1_LoadersareAwesome.srt"                                               "Lesson 4C_ Hooking it Up with Loaders"\"01 - Loaders are Awesome.chs.srt"
copy ..\"Developing Android Apps Lession4C"\"4c_2_OnLoaders.srt"                                                       "Lesson 4C_ Hooking it Up with Loaders"\"02 - On Loaders.chs.srt"
copy ..\"Developing Android Apps Lession4C"\"4c_3_DisadvantagesQuiz.srt"                                               "Lesson 4C_ Hooking it Up with Loaders"\"03 - Disadvantages Quiz.chs.srt"
copy ..\"Developing Android Apps Lession4C"\"4c_4_DisadvantagesSolution.srt"                                           "Lesson 4C_ Hooking it Up with Loaders"\"04 - Disadvantages Solution.chs.srt"
copy ..\"Developing Android Apps Lession4C"\"4c_5_UseCursorLoaderwithWeatherProvider.srt"                              "Lesson 4C_ Hooking it Up with Loaders"\"05 - Use CursorLoader with WeatherProvider.chs.srt"
copy ..\"Developing Android Apps Lession4C"\"4c_6_LeveragingLoaders.srt"                                               "Lesson 4C_ Hooking it Up with Loaders"\"06 - Leveraging Loaders.chs.srt"
copy ..\"Developing Android Apps Lession4C"\"4c_7_LeveragingLoadersQuiz.srt"                                           "Lesson 4C_ Hooking it Up with Loaders"\"07 - Leveraging Loaders Quiz.chs.srt"
copy ..\"Developing Android Apps Lession4C"\"4c_8_LeveragingLoadersSolution.srt"                                       "Lesson 4C_ Hooking it Up with Loaders"\"08 - Leveraging Loaders Solution.chs.srt"
copy ..\"Developing Android Apps Lession4C"\"4c_9_LeveragingProjections.srt"                                           "Lesson 4C_ Hooking it Up with Loaders"\"09 - Leveraging Projections.chs.srt"
copy ..\"Developing Android Apps Lession4C"\"4c_10_LeveragingProjectionsQuiz.srt"                                      "Lesson 4C_ Hooking it Up with Loaders"\"10 - Leveraging Projections Quiz.chs.srt"
copy ..\"Developing Android Apps Lession4C"\"4c_11_LeveragingProjectionsSolution.srt"                                  "Lesson 4C_ Hooking it Up with Loaders"\"11 - Leveraging Projections Solution.chs.srt"
copy ..\"Developing Android Apps Lession4C"\"4c_12_MakeDetailsViewFunctional-Quiz.srt"                                 "Lesson 4C_ Hooking it Up with Loaders"\"12 - Make Details View Functional - Quiz.chs.srt"
copy ..\"Developing Android Apps Lession4C"\"4c_13_MakeDetailsViewFunctionalSolution.srt"                              "Lesson 4C_ Hooking it Up with Loaders"\"13 - Make Details View Functional Solution.chs.srt"
copy ..\"Developing Android Apps Lession4C"\"4c_14_MakingyourContentProviderAccessible.srt"                            "Lesson 4C_ Hooking it Up with Loaders"\"14 - Making your ContentProvider Accessible.chs.srt"
copy ..\"Developing Android Apps Lession4C"\"4c_15_3rd Party Content Providers - Developing Android Apps.srt"          "Lesson 4C_ Hooking it Up with Loaders"\"15 - 3rd Party Content Providers.chs.srt"
copy ..\"Developing Android Apps Lession4C"\"4c_16_3rd Party Content Providers Solution.srt"                           "Lesson 4C_ Hooking it Up with Loaders"\"16 - 3rd Party Content Providers Solution.chs.srt"
copy ..\"Developing Android Apps Lession4C"\"4c_17_Lesson 4 Recap with Reto and Dan - Developing Android Apps.srt"     "Lesson 4C_ Hooking it Up with Loaders"\"17 - Lesson 4 Recap with Reto and Dan.chs.srt"
copy ..\"Developing Android Apps Lession4C"\"4c_18_Storytime Android Hardware - Developing Android Apps.srt"           "Lesson 4C_ Hooking it Up with Loaders"\"18 - Storytime Android Hardware.chs.srt"
