mkdir "Lesson 3_ New Activities and Intents"
copy ..\"Developing Android Apps Lession3"\"03_01_Introduction to Lesson 3.srt"                      "Lesson 3_ New Activities and Intents"\"01 - Introduction to Lesson 3.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_02_What to do next.srt"                               "Lesson 3_ New Activities and Intents"\"02 - What to do next.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_03_Sunshine App UX Mocks.srt"                         "Lesson 3_ New Activities and Intents"\"03 - Sunshine App UX Mocks.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_04_List Item Click Listener.srt"                      "Lesson 3_ New Activities and Intents"\"04 - List Item Click Listener.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_05_List Item Click Listener Solution.srt"             "Lesson 3_ New Activities and Intents"\"05 - List Item Click Listener.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_06_ItemClickListener and Toast.srt"                   "Lesson 3_ New Activities and Intents"\"06 - ItemClickListener and Toast.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_07_Create New Activity.srt"                           "Lesson 3_ New Activities and Intents"\"08 - Create New Activity.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_08_ItemClickListener and Toast Solution.srt"          "Lesson 3_ New Activities and Intents"\"07 - ItemClickListener and Toast Solution.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_09_Create New Activity Solution.srt"                  "Lesson 3_ New Activities and Intents"\"09 - Create New Activity.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_10_Intents Framework.srt"                             "Lesson 3_ New Activities and Intents"\"10 - Intents Framework.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_11_Intents as Envelopes.srt"                          "Lesson 3_ New Activities and Intents"\"11 - Intents as Envelopes.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_12_Launch DetailActivity.srt"                         "Lesson 3_ New Activities and Intents"\"12 - Launch DetailActivity.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_13_Launch DetailActivity Solution.srt"                "Lesson 3_ New Activities and Intents"\"13 - Launch DetailActivity.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_14_Display Content in DetailActivity.srt"             "Lesson 3_ New Activities and Intents"\"14 - Display Content in DetailActivity.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_15_Display Content in DetailActivity Solution.srt"    "Lesson 3_ New Activities and Intents"\"15 - Display Content in DetailActivity.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_16_It works.srt"                                      "Lesson 3_ New Activities and Intents"\"16 - It works.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_17_Settings UX.srt"                                   "Lesson 3_ New Activities and Intents"\"17 - Settings UX.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_18_Preferences.srt"                                   "Lesson 3_ New Activities and Intents"\"18 - Preferences.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_19_Create SettingsActivity.srt"                       "Lesson 3_ New Activities and Intents"\"19 - Create SettingsActivity.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_20_Create SettingsActivity Solution.srt"              "Lesson 3_ New Activities and Intents"\"20 - Create SettingsActivity.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_21_Launch SettingsActivity.srt"                       "Lesson 3_ New Activities and Intents"\"21 - Launch SettingsActivity.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_22_Launch SettingsActivity Solution.srt"              "Lesson 3_ New Activities and Intents"\"22 - Launch SettingsActivity.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_23_Location Setting XML.srt"                          "Lesson 3_ New Activities and Intents"\"23 - Location Setting XML.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_24_Modify SettingsActivity.srt"                       "Lesson 3_ New Activities and Intents"\"24 - Modify SettingsActivity.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_25_Use SharedPreferences.srt"                         "Lesson 3_ New Activities and Intents"\"25 - Use SharedPreferences.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_26_Use SharedPreferences Solution.srt"                "Lesson 3_ New Activities and Intents"\"26 - Use SharedPreferences Solution.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_27_Update Data on Activity Start.srt"                 "Lesson 3_ New Activities and Intents"\"27 - Update Data on Activity Start.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_28_Temperature Units Setting.srt"                     "Lesson 3_ New Activities and Intents"\"28 - Temperature Units Setting.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_29_Temperature Units Setting Solution.srt"            "Lesson 3_ New Activities and Intents"\"29 - Temperature Units Setting Solution.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_30_Debug Breakpoints.srt"                             "Lesson 3_ New Activities and Intents"\"30 - Debug Breakpoints.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_31_Launching Implicit Intents.srt"                    "Lesson 3_ New Activities and Intents"\"31 - Launching Implicit Intents.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_32_Add Map Location Intent.srt"                       "Lesson 3_ New Activities and Intents"\"32 - Add Map Location Intent.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_33_Add Map Location Intent Solution.srt"              "Lesson 3_ New Activities and Intents"\"33 - Add Map Location Intent Solution.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_34_Intent Resolution.srt"                             "Lesson 3_ New Activities and Intents"\"34 - Intent Resolution.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_35_Share Intent is Awesome.srt"                       "Lesson 3_ New Activities and Intents"\"35 - Share Intent is Awesome.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_36_Share Intent Solution.srt"                         "Lesson 3_ New Activities and Intents"\"36 - Share Intent Solution.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_37_Broadcast Intents.srt"                             "Lesson 3_ New Activities and Intents"\"37 - Broadcast Intents.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_38_Intent Filters.srt"                                "Lesson 3_ New Activities and Intents"\"38 - Intent Filters.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_39_Intent Filters Solution.srt"                       "Lesson 3_ New Activities and Intents"\"39 - Intent Filters Solution.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_40_Lesson 3 Recap.srt"                                "Lesson 3_ New Activities and Intents"\"40 - Lesson 3 Recap.chs.srt"
copy ..\"Developing Android Apps Lession3"\"03_41_Storytime Android Distribution Platform.srt"       "Lesson 3_ New Activities and Intents"\"41 - Storytime Android Distribution Platform.chs.srt"
